name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mpm deps
        run: |
          apt update
          apt install wget unzip ca-certificates -y

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b

      - name: Test
      uses: matlab-actions/run-command@v2
      with:
        command: disp("hello")

      - name: Run process
        uses: matlab-actions/run-tests@v2
