name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Run command
        uses: matlab-actions/run-command@v1
        with:
          command: disp("Hello Debian!")
