name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mpm deps
        run: |
          apt update
          apt install wget unzip ca-certificates -y

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Run command
        uses: matlab-actions/run-command@v1
        with:
          command: disp("Hello Debian!!")

      - name: Run tests
        uses: matlab-actions/run-tests@v1
        with:
          startup-options: -sd startup
